### ISSUE TITLE
Real-time aggregates not showing new values after first creation

### ISSUE THREAD

**Issue by sebaspf** [timescale/docs#1217]
# Describe the bug

When following the example on [this page](https://docs.timescale.com/getting-started/latest/create-cagg/create-cagg-basics/#create-a-continuous-aggregate-from-aggregate-query) that creates the continuous aggregates for a table that already contains data, the last bucket (normally incomplete) gets materialized (from the plot in the docs). 

## Issue

Inserting new values that correspond to the last incomplete materialized bucket do not update the aggregation result as one would expect from the docs on real-time. First when the inserts start a new bucket, the values update as expected.

# Page affected

https://docs.timescale.com/getting-started/latest/create-cagg/create-cagg-basics/#create-a-continuous-aggregate-from-aggregate-query
and probably others describing this behavior

# Version affected

Tested on 2.6 and 2.7

# Subject matter expert (SME)

David Kohn
https://stackoverflow.com/questions/69404500/real-time-aggregation-not-up-to-date
https://www.youtube.com/watch?v=1V1ADr6CKz4&list=PLsceB9ac9MHRnmNZrCn_TWkUrCBCPR3mc&index=10

**Comment by charislam** [comment]
Thanks so much for the report, sebaspf. Really appreciate it!

Notes to docs team:
This is covered here (https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/troubleshooting/) but we should find ways of cleaning this up and making it more visible. (For one thing, title does not show up in TOC because it is at the wrong level.
