### ISSUE TITLE
[Docs RFC] Promscale Install docs

### ISSUE THREAD

**Issue by Rajakavitha1** [timescale/docs#1275]
# Describe the change in content, appearance, or functionality

The Installation section needs to be refactored to account for the actual install steps that the users follow:
Here's the proposed structure:

**Install Promscale**
-  Resource recommendation ( because this section describes the compute and disk requirements that are recommended for Promscale, based on the ingest rate and retention.)
-  Kubernetes
    -  Helm Charts
    - Manifest File
    -  TOBS ( because it deploys The observability stack (tobs) in a Kubernetes cluster.)
-  Docker
- Self Hosted
   *  Binary
   * Debian or Ubuntu
   * RPM based Linux (Red Hat or CentOS)
- Configuration recommendation (because after you deploy these are the recommended configurations). We need to create partials for this and append it as What's next in all the installs.

# Subject matter expert (SME)

@ramonguiu 

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

**Comment by Rajakavitha1** [comment]
H,i @Loquacity. Please let me know if the proposed IA works?

**Comment by VineethReddy02** [comment]
Hi, @Rajakavitha1 this takes us back to the existing structure in the docs website. I do not think recommendations should be part of installation section but if the docs team has reasoning on why and how would it add value, open to hearing out thoughts and suggestions. 

**Install Promscale**
* Resource recommendation ( because this section describes the compute and disk requirements that are recommended for Promscale, based on the ingest rate and retention.)
* Configuration recommendation (because after you deploy these are the recommended configurations). We need to create partials for this and append it as What's next in all the installs.

**Comment by Loquacity** [comment]
> I do not think recommendations should be part of installation section

Why?

**Comment by VineethReddy02** [comment]
Because the Install section or tree should be all about different installation modes, these are recommendations maintaining a dedicated tree will be easier to outline all recommendations.

**Comment by VineethReddy02** [comment]
LGTM! I want this structure in PR to understand the IA experience. The only concern I have is recommendations should be outside the installation section, but you have fair point on having it inside makes navigation easy.  So let's do the change and measure the engagement.

**Comment by Rajakavitha1** [comment]
@VineethReddy02 Closing this Issue for now because the scope of work for documentation team with Promscale is now limited to language, grammar, and style edits. We can take on the IA initiatives further down the line when there is a requirement from the Promscale team.
