### ISSUE TITLE
Document how to `UNNEST` data from `lttb` queries when using `GROUP BY`

### ISSUE THREAD

**Issue by charislam** [timescale/docs#1798]
https://timescaledb.slack.com/archives/C02LXMKJMMJ/p1669212709046399

**Comment by Loquacity** [comment]
@jonatas @noctarius Since you were in on the original convo here, can you please help me out with getting this updated? I think we just need another example added in here, showing how to use it in a GROUP BY: https://docs.timescale.com/api/latest/hyperfunctions/downsample/lttb/#sample-usage What do you think?
