### ISSUE TITLE
[Feedback] Improve import CSV content on page: /timescaledb/latest/how-to-guides/migrate-data/import-csv/

### ISSUE THREAD

**Issue by TomasMiloCA** [timescale/docs#1894]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

Is there a complete example that I can follow with the specific parameters needed to upload the CSV to the online table and database.

**Comment by Loquacity** [comment]
Hi @TomasMiloCA I've added this to the backlog to improve the documentation on this page. In the meantime, feel free to reach out to our community for help with getting your import working: https://www.timescale.com/community

**Comment by Loquacity** [comment]
Looking at the instructions on this page, it's a little hard to make it more concrete, as it depends largely on the data you are importing. Even if we were to provide a full worked example, it would be different to whatever a reader would do, simply because the underlying data and schema is different. The instructions work as they stand, so I can't see a way to improve this content as of today.
