### ISSUE TITLE
[Docs RFC] On the Decompression page, add a note about checking for uncompressed chunks

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#2468]
# Describe change in content, appearance, or functionality

On the Decompression page, under the section about decompressing by time, add a note about checking for chunks that are not compressed before running the decompression. If you try to decompress an uncompressed chunk, an error is thrown. You can add the check by setting `if_compressed` to `true`.  

# Subject matter expert (SME)

@tanyatimescale @iroussos @antekresic 

# Deadline

[When does this need to be addressed]

# Any further info

- Docs: https://docs.timescale.com/use-timescale/latest/compression/decompress-chunks/#decompress-chunks-by-time
- Link to Slack conversation: https://iobeam.slack.com/archives/C0J94TE4F/p1687540407548859

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by Rajakavitha1** [comment]
Hi @antekresic  could you please let me know the error message that would appear so that the not in the documentation can be more precise: " When you decompress chunks by time range and if there are any uncompressed chunks in that time range, then the error `xyz` appears. Ensure that you set the optional argument `if_compressed` to `true` when you decompress chunks by time range so that those chunks are skipped."

**Comment by Rajakavitha1** [comment]
Marking this as closed because this has now been addressed. The optional argument in the example checked for uncompressed chunks.
