### ISSUE TITLE
Legacy Timescale documentation site inaccessible (Cloudflare 520)

### ISSUE THREAD

**Issue by richbon75** [timescale/docs#3208]
Hi!  Something's gone wrong with the legacy docs site.

As noted in https://github.com/timescale/docs/issues/26 the legacy docs for Timescale v1.7 should be available at https://legacy-docs.timescale.com/v1.7/main  (and in fact, this is the URL the current documentation page links to when you try to navigate to it)

Unfortunately, the page has been returning as a Cloudflare 520 error for some time, so I suspect something's not working as it should.

I'm dealing with a legacy installation and it would be great to be able to reference the correct documentation for it!  Thanks so much!

**Comment by billy-the-fish** [comment]
Hi Rich, thanks for reaching out. Glad to hear the v1.7 is still running well for you. I'm afraid that v1.7 has been deprecated for a while now and we are removing the versions from the docs rather than replacing them. 

I found the source for TimescaleDB v1.7 docs for you: https://github.com/timescale/docs.timescale.com-content/tree/v1.7.0 I hope this is helpful. I tried to supply a working version of the site. Sadly, the doc build no longer supports that structure. 

Tell me if having the source docs help enough. I will have another go with the build if you need the interactive site.

**Comment by richbon75** [comment]
Hi Billy - Thanks for trying, and thanks for including that link to the source.  I should be able to dig through there to find what I need.
