### ISSUE TITLE
[Docs RFC] Update the High availability doc for the latest features

### ISSUE THREAD

**Issue by billy-the-fish** [timescale/docs#3372]
New features are coming to https://docs.timescale.com/use-timescale/latest/ha-replicas/high-availability/. 

@ggodeke to supply best practice for the new types of replication, and access to the UI. 
@billy-the-fish to update the docs. Small changes for the new features and a language review for the page.

**Comment by esclymeTS** [comment]
Some bullets on the updates:

- We’re adding self serve options for customers to select multiple HA Replicas (which we’re calling Highest Availability, ss#1) and Synchronous Replication (which we’re calling High Data Integrity, ss#2)
- Previously, HA replicas defaulted to async which we’re calling High Performance (ss#2). 
- Both Highest Availability (multi) and High Data Integrity (synchronous) are only available to Scale & Enterprise tiers (hence the Upgrade prompts in both screenshots) 
- Customers can only select synchronous replication for a up to two HA replicas

Customer Context:

- Mission Critical Applications may want to opt for synchronous/High data integrity. There’s the lowest potential for data loss. Synchronous also allows for immediate failover to the replica (where async replication would need to catch up). Finally, if database lag/latency is not an issue due to AZ geographical proximity, customers should/would choose sync replication
- However, if zone latency is high, perf matters more than data integrity, and cost considerations are paramount, customers should opt for Asynchronous Replication

https://docs.google.com/document/d/1WAgVphChiXOynDSWHwS9n0U_mDTw2BBsutMf6MYd0Yo/edit
