### ISSUE TITLE
Document installation via MacPorts

### ISSUE THREAD

**Issue by blair** [timescale/docs#757]
**Relevant system information:**
 - OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]: MacOS

I just added support for installing timescaledb via MacPorts:

  `port -v install timescaledb +postgresqlXX`

where XX is the appropriate variant, e.g. 96, 10, 11, 12.

Can this be added to your docs?

**Comment by Rajakavitha1** [comment]
@blair can you please confirm if timescaledb-tune is also installed when timescaledb and postgresql is installed using MacPorts. Because is installed as a dependency when you install via Homebrew. This is the important because to help make configuring TimescaleDB a little easier, we created a tool called [timescaledb-tune](https://github.com/timescale/timescaledb-tune) that handles setting the most common parameters to good values based on your system. It accounts for memory, CPU, and PostgreSQL version.  

Here's the output from the macOS that i tried the installation.

rajie@RajakavithasMBP ~ % psql -U postgres -h localhost
psql (14.1)
Type "help" for help.

postgres=# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description          
---------+---------+------------+------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(1 row)

postgres=# exit
rajie@RajakavithasMBP ~ % ports timescaledb contents
zsh: command not found: ports
rajie@RajakavithasMBP ~ % port contents timescaledb
Port timescaledb contains:
  /opt/local/lib/postgresql14/timescaledb-2.5.2.so
  /opt/local/lib/postgresql14/timescaledb.so
  /opt/local/share/postgresql14/extension/timescaledb--1.7.0--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--1.7.1--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--1.7.2--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--1.7.3--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--1.7.4--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--1.7.5--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.0.0--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.0.0-rc1--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.0.0-rc2--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.0.0-rc3--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.0.0-rc4--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.0.1--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.0.2--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.1.0--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.1.1--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.2.0--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.2.1--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.3.0--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.3.1--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.4.0--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.4.1--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.4.2--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.5.0--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.5.1--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb--2.5.2.sql
  /opt/local/share/postgresql14/extension/timescaledb.control
rajie@RajakavithasMBP ~ % sudo timescaledb-tune
Password:
sudo: timescaledb-tune: command not found
rajie@RajakavithasMBP ~ %

**Comment by blair** [comment]
The port doesn't install any of the files in https://github.com/timescale/timescaledb-tune. Probably the best way is to make a new `timescaledb-tools` port that installs the files.

**Comment by Rajakavitha1** [comment]
> The port doesn't install any of the files in https://github.com/timescale/timescaledb-tune. Probably the best way is to make a new `timescaledb-tools` port that installs the files.

Thanks @blair that would be awesome. However, I would like to get the thoughts of from the rest of the team at timescale. @solugebefola @NunoFilipeSantos @RobAtticus @Loquacity  please share your thoughts because we recommend timescales-tools .

**Comment by Loquacity** [comment]
> > The port doesn't install any of the files in https://github.com/timescale/timescaledb-tune. Probably the best way is to make a new `timescaledb-tools` port that installs the files.
> 
> Thanks @blair that would be awesome. However, I would like to get the thoughts from the rest of the team at timescale. @solugebefola @NunoFilipeSantos @RobAtticus @Loquacity please share your thoughts because we recommend timescaledb-tools .

From a docs perspective, if the procedure changes, we'll update the docs. For now, let's just document what exists.

**Comment by Rajakavitha1** [comment]
> The port doesn't install any of the files in https://github.com/timescale/timescaledb-tune. Probably the best way is to make a new `timescaledb-tools` port that installs the files.

Hi @blair  I just submitted a PR with the instructions to install using MacPorts. Do you have any updates about `timescaledb-tools` port? that would make it seamless as homebrew installation.
