### ISSUE TITLE
[Content Bug] Lack of clarity about supported parameters in time_bucket within caggs and other time_bucket and cagg issues

### ISSUE THREAD

**Issue by greenweeds** [timescale/docs#910]
# Describe the bug

Following the example results in an error: 

```
ERROR:  only immutable expressions allowed in time bucket function
HINT:  Use an immutable expression as third argument to the time bucket function.
```

## What do the docs say now?

Please see the discussion in https://github.com/timescale/timescaledb/issues/4117 as I am not 100% sure of the correction and where the corrections need to be made. Specifically this comment: https://github.com/timescale/timescaledb/issues/4117#issuecomment-1047562009 

## What should the docs say?

# Page affected
https://docs.timescale.com/api/latest/hyperfunctions/time_bucket_ng/#timescaledb-experimental-time-bucket-ng

# Version affected

latest

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots
![Screenshot 2022-03-08 at 09 27 57](https://user-images.githubusercontent.com/3043487/157208027-9d994de4-5069-47d9-bb12-932946d6ccfc.png)

# Any further info

[Anything else you want to add, or further links]

**Comment by charislam** [comment]
Partially addressing as part of #904:
- `time_bucket` and `time_bucket_ng` by themselves can take parameters that aren't allowed in continuous aggregates, including casts to `timestamp` and named parameters (add callout to explain)
- better explain origins and highlight the origin limitation in `time_bucket_ng`

Needs a separate PR:
@afiskon, you're absolutely certain `NULL` isn't supported in `add_continuous_aggregate_policy`? It is supported in [`refresh_continuous_aggregate`](https://docs.timescale.com/api/latest/continuous-aggregates/refresh_continuous_aggregate/), so one might expect it to be supported in the other as well. If they are different, I'll add an explicit note in the docs.

**Comment by afiskon** [comment]
@charislam I believe it IS supported. The problem is that the exact semantics of it is not documented. So, from the user perspective, it can do anything. ( https://docs.timescale.com/api/latest/continuous-aggregates/add_continuous_aggregate_policy/#add-continuous-aggregate-policy )

Personally I'm not 100% certain what the semantics is supposed to be. Hopefully somebody from @timescale/database-eng knows. As I recall add_continuous_aggregate_policy() can have start_offset => NULL, but it does something not obvious, like deleting the old data from the aggregate when the corresponding partition gets deleted. `end_offset` and `schedule_interval` to my knowledge can't be NULL.

**Comment by gayyappan** [comment]
@charislam for add_continuous_aggregate_policy
schedule_interval cannot be NULL.
start_offset  and end_offset can be NULL. The semantics is exactly the same as refresh_continuous_aggregate.
( But we would definitely not recommend setting end_offset to NULL in the policy.  That would mean that the leading time_bucket that is materialized is continually being updated - this is a use case for real time aggregates).
In fact, if we have any documentation that shows end_offset as NULL, we should remove that - it is a bad practice.
